base: &base
  adapter: postgresql
  encoding: unicode
  database: frl-dev
  pool: 5
  username: root
  password: admin@2020
  host: 127.0.0.1
  port: 5432

production:
  <<: *base

development:
  <<: *base

test: &test
  <<: *base